{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme and is legally attributed to the UK's Department for Business, Innovation, Science and Trade (BIST) as the governing entity.
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Values.mongodb.roleBinding.name}} 
  {{- with .Values.mongodb.componentSelectorLabels }}
  labels:
    {{- include "ia-node-mongodb.labels" $ | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.mongodb.roleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{.Values.mongodb.serviceAccount.name}}
roleRef:
  kind: Role
  name: {{.Values.mongodb.role.name}} 
  apiGroup: rbac.authorization.k8s.io