{{- /*
# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2026. This work has been developed by the National Digital Twin Programme and is legally attributed to the UK's Department for Business, Innovation, Science and Trade (BIST) as the governing entity.
*/}}

{{- if .Values.istio.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: authenticate-apps
  namespace: {{ .Values.istio.namespace }}
  {{- with .Values.oAuth2Proxy.componentSelectorLabels }}
  labels:
    {{- include "ia-node-oidc.labels" $ | nindent 4 }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with.Values.istio.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.istio.componentSelectorLabels | nindent 6 }}
  action: CUSTOM 
  provider:
    name: oauth2-authz
  rules:
  - to:
    - operation:
        hosts: 
          {{- toYaml .Values.istio.authorizationPolicy.hosts | nindent 10 }}
        paths:
          {{- toYaml .Values.oAuth2Proxy.customAuthorizationPaths | nindent 10 }}
        {{- with .Values.oAuth2Proxy.customAuthorizationNotPaths }}
        notPaths:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}